// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2kzxwpSZxGae6N1Ctzdw8NktH6rOs1GU',
    appId: '1:326028224308:web:695c4c3f24a075b527a761',
    messagingSenderId: '326028224308',
    projectId: 'edule-app',
    authDomain: 'edule-app.firebaseapp.com',
    storageBucket: 'edule-app.appspot.com',
    measurementId: 'G-PG64S51WG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzEyBhoEXQLx-3H_qgsKc_3rac79ePM2k',
    appId: '1:326028224308:android:2137adc77ca9774227a761',
    messagingSenderId: '326028224308',
    projectId: 'edule-app',
    storageBucket: 'edule-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3HRfynSs620reaD9Qx8Jpxc6WASCSz30',
    appId: '1:326028224308:ios:7a58643773a7813227a761',
    messagingSenderId: '326028224308',
    projectId: 'edule-app',
    storageBucket: 'edule-app.appspot.com',
    iosClientId: '326028224308-u2o7uv1qssojkv8pc9mpdknd0i8jo95s.apps.googleusercontent.com',
    iosBundleId: 'com.example.edule',
  );
}
